/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ZipArchiveApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ZipArchiveApiTests
    {
        private ZipArchiveApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ZipArchiveApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZipArchiveApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ZipArchiveApi
            //Assert.IsInstanceOfType(typeof(ZipArchiveApi), instance, "instance is a ZipArchiveApi");
        }

        
        /// <summary>
        /// Test ZipArchiveZipCreate
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile1 = null;
            //System.IO.Stream inputFile2 = null;
            //System.IO.Stream inputFile3 = null;
            //System.IO.Stream inputFile4 = null;
            //System.IO.Stream inputFile5 = null;
            //System.IO.Stream inputFile6 = null;
            //System.IO.Stream inputFile7 = null;
            //System.IO.Stream inputFile8 = null;
            //System.IO.Stream inputFile9 = null;
            //System.IO.Stream inputFile10 = null;
            //var response = instance.ZipArchiveZipCreate(inputFile1, inputFile2, inputFile3, inputFile4, inputFile5, inputFile6, inputFile7, inputFile8, inputFile9, inputFile10);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test ZipArchiveZipCreateAdvanced
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateZipArchiveRequest request = null;
            //var response = instance.ZipArchiveZipCreateAdvanced(request);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipCreateEncrypted
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateEncryptedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string password = null;
            //System.IO.Stream inputFile1 = null;
            //string encryptionAlgorithm = null;
            //System.IO.Stream inputFile2 = null;
            //System.IO.Stream inputFile3 = null;
            //System.IO.Stream inputFile4 = null;
            //System.IO.Stream inputFile5 = null;
            //System.IO.Stream inputFile6 = null;
            //System.IO.Stream inputFile7 = null;
            //System.IO.Stream inputFile8 = null;
            //System.IO.Stream inputFile9 = null;
            //System.IO.Stream inputFile10 = null;
            //var response = instance.ZipArchiveZipCreateEncrypted(password, inputFile1, encryptionAlgorithm, inputFile2, inputFile3, inputFile4, inputFile5, inputFile6, inputFile7, inputFile8, inputFile9, inputFile10);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test ZipArchiveZipCreateQuarantine
        /// </summary>
        [Test]
        public void ZipArchiveZipCreateQuarantineTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ZipArchiveZipCreateQuarantine();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipDecrypt
        /// </summary>
        [Test]
        public void ZipArchiveZipDecryptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //string zipPassword = null;
            //var response = instance.ZipArchiveZipDecrypt(inputFile, zipPassword);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipEncryptAdvanced
        /// </summary>
        [Test]
        public void ZipArchiveZipEncryptAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ZipEncryptionAdvancedRequest encryptionRequest = null;
            //var response = instance.ZipArchiveZipEncryptAdvanced(encryptionRequest);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ZipArchiveZipExtract
        /// </summary>
        [Test]
        public void ZipArchiveZipExtractTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.ZipArchiveZipExtract(inputFile);
            //Assert.IsInstanceOf<ZipExtractResponse> (response, "response is ZipExtractResponse");
        }
        
    }

}
