/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing AppendXlsxRowRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppendXlsxRowRequestTests
    {
        // TODO uncomment below to declare an instance variable for AppendXlsxRowRequest
        //private AppendXlsxRowRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppendXlsxRowRequest
            //instance = new AppendXlsxRowRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppendXlsxRowRequest
        /// </summary>
        [Test]
        public void AppendXlsxRowRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppendXlsxRowRequest
            //Assert.IsInstanceOfType<AppendXlsxRowRequest> (instance, "variable 'instance' is a AppendXlsxRowRequest");
        }


        /// <summary>
        /// Test the property 'InputFileBytes'
        /// </summary>
        [Test]
        public void InputFileBytesTest()
        {
            // TODO unit test for the property 'InputFileBytes'
        }
        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'WorksheetToUpdate'
        /// </summary>
        [Test]
        public void WorksheetToUpdateTest()
        {
            // TODO unit test for the property 'WorksheetToUpdate'
        }
        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [Test]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }

    }

}
