/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing BeginEditingChunkRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeginEditingChunkRequestTests
    {
        // TODO uncomment below to declare an instance variable for BeginEditingChunkRequest
        //private BeginEditingChunkRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeginEditingChunkRequest
            //instance = new BeginEditingChunkRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeginEditingChunkRequest
        /// </summary>
        [Test]
        public void BeginEditingChunkRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeginEditingChunkRequest
            //Assert.IsInstanceOfType<BeginEditingChunkRequest> (instance, "variable 'instance' is a BeginEditingChunkRequest");
        }


        /// <summary>
        /// Test the property 'DocumentID'
        /// </summary>
        [Test]
        public void DocumentIDTest()
        {
            // TODO unit test for the property 'DocumentID'
        }
        /// <summary>
        /// Test the property 'Base64EncodedChunk'
        /// </summary>
        [Test]
        public void Base64EncodedChunkTest()
        {
            // TODO unit test for the property 'Base64EncodedChunk'
        }
        /// <summary>
        /// Test the property 'ChunkIndex'
        /// </summary>
        [Test]
        public void ChunkIndexTest()
        {
            // TODO unit test for the property 'ChunkIndex'
        }
        /// <summary>
        /// Test the property 'ChunkTotalCount'
        /// </summary>
        [Test]
        public void ChunkTotalCountTest()
        {
            // TODO unit test for the property 'ChunkTotalCount'
        }

    }

}
