/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ClearXlsxRowRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClearXlsxRowRequestTests
    {
        // TODO uncomment below to declare an instance variable for ClearXlsxRowRequest
        //private ClearXlsxRowRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClearXlsxRowRequest
            //instance = new ClearXlsxRowRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClearXlsxRowRequest
        /// </summary>
        [Test]
        public void ClearXlsxRowRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClearXlsxRowRequest
            //Assert.IsInstanceOfType<ClearXlsxRowRequest> (instance, "variable 'instance' is a ClearXlsxRowRequest");
        }


        /// <summary>
        /// Test the property 'InputFileBytes'
        /// </summary>
        [Test]
        public void InputFileBytesTest()
        {
            // TODO unit test for the property 'InputFileBytes'
        }
        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'WorksheetToEdit'
        /// </summary>
        [Test]
        public void WorksheetToEditTest()
        {
            // TODO unit test for the property 'WorksheetToEdit'
        }
        /// <summary>
        /// Test the property 'RowIndex'
        /// </summary>
        [Test]
        public void RowIndexTest()
        {
            // TODO unit test for the property 'RowIndex'
        }

    }

}
