/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ConvertedPngDirectPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConvertedPngDirectPageTests
    {
        // TODO uncomment below to declare an instance variable for ConvertedPngDirectPage
        //private ConvertedPngDirectPage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConvertedPngDirectPage
            //instance = new ConvertedPngDirectPage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConvertedPngDirectPage
        /// </summary>
        [Test]
        public void ConvertedPngDirectPageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConvertedPngDirectPage
            //Assert.IsInstanceOfType<ConvertedPngDirectPage> (instance, "variable 'instance' is a ConvertedPngDirectPage");
        }


        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'ImageData'
        /// </summary>
        [Test]
        public void ImageDataTest()
        {
            // TODO unit test for the property 'ImageData'
        }

    }

}
