/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing CsvCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CsvCollectionTests
    {
        // TODO uncomment below to declare an instance variable for CsvCollection
        //private CsvCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CsvCollection
            //instance = new CsvCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CsvCollection
        /// </summary>
        [Test]
        public void CsvCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CsvCollection
            //Assert.IsInstanceOfType<CsvCollection> (instance, "variable 'instance' is a CsvCollection");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CsvFiles'
        /// </summary>
        [Test]
        public void CsvFilesTest()
        {
            // TODO unit test for the property 'CsvFiles'
        }
        /// <summary>
        /// Test the property 'FileCount'
        /// </summary>
        [Test]
        public void FileCountTest()
        {
            // TODO unit test for the property 'FileCount'
        }

    }

}
