/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocumentItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentItemTests
    {
        // TODO uncomment below to declare an instance variable for DocumentItem
        //private DocumentItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentItem
            //instance = new DocumentItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentItem
        /// </summary>
        [Test]
        public void DocumentItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentItem
            //Assert.IsInstanceOfType<DocumentItem> (instance, "variable 'instance' is a DocumentItem");
        }


        /// <summary>
        /// Test the property 'DocumentFileName'
        /// </summary>
        [Test]
        public void DocumentFileNameTest()
        {
            // TODO unit test for the property 'DocumentFileName'
        }
        /// <summary>
        /// Test the property 'DocumentContent'
        /// </summary>
        [Test]
        public void DocumentContentTest()
        {
            // TODO unit test for the property 'DocumentContent'
        }

    }

}
