/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocxTableSingleTableFill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocxTableSingleTableFillTests
    {
        // TODO uncomment below to declare an instance variable for DocxTableSingleTableFill
        //private DocxTableSingleTableFill instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocxTableSingleTableFill
            //instance = new DocxTableSingleTableFill();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocxTableSingleTableFill
        /// </summary>
        [Test]
        public void DocxTableSingleTableFillInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocxTableSingleTableFill
            //Assert.IsInstanceOfType<DocxTableSingleTableFill> (instance, "variable 'instance' is a DocxTableSingleTableFill");
        }


        /// <summary>
        /// Test the property 'TableStartTag'
        /// </summary>
        [Test]
        public void TableStartTagTest()
        {
            // TODO unit test for the property 'TableStartTag'
        }
        /// <summary>
        /// Test the property 'TableEndTag'
        /// </summary>
        [Test]
        public void TableEndTagTest()
        {
            // TODO unit test for the property 'TableEndTag'
        }
        /// <summary>
        /// Test the property 'DataToFillIn'
        /// </summary>
        [Test]
        public void DataToFillInTest()
        {
            // TODO unit test for the property 'DataToFillIn'
        }

    }

}
