/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocxTableTableFillMultiRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocxTableTableFillMultiRequestTests
    {
        // TODO uncomment below to declare an instance variable for DocxTableTableFillMultiRequest
        //private DocxTableTableFillMultiRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocxTableTableFillMultiRequest
            //instance = new DocxTableTableFillMultiRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocxTableTableFillMultiRequest
        /// </summary>
        [Test]
        public void DocxTableTableFillMultiRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocxTableTableFillMultiRequest
            //Assert.IsInstanceOfType<DocxTableTableFillMultiRequest> (instance, "variable 'instance' is a DocxTableTableFillMultiRequest");
        }


        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'InputFileData'
        /// </summary>
        [Test]
        public void InputFileDataTest()
        {
            // TODO unit test for the property 'InputFileData'
        }
        /// <summary>
        /// Test the property 'TablesToFill'
        /// </summary>
        [Test]
        public void TablesToFillTest()
        {
            // TODO unit test for the property 'TablesToFill'
        }

    }

}
