/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocxMetadataCustomProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocxMetadataCustomPropertyTests
    {
        // TODO uncomment below to declare an instance variable for DocxMetadataCustomProperty
        //private DocxMetadataCustomProperty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocxMetadataCustomProperty
            //instance = new DocxMetadataCustomProperty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocxMetadataCustomProperty
        /// </summary>
        [Test]
        public void DocxMetadataCustomPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocxMetadataCustomProperty
            //Assert.IsInstanceOfType<DocxMetadataCustomProperty> (instance, "variable 'instance' is a DocxMetadataCustomProperty");
        }


        /// <summary>
        /// Test the property 'PropertyName'
        /// </summary>
        [Test]
        public void PropertyNameTest()
        {
            // TODO unit test for the property 'PropertyName'
        }
        /// <summary>
        /// Test the property 'PropertyDataType'
        /// </summary>
        [Test]
        public void PropertyDataTypeTest()
        {
            // TODO unit test for the property 'PropertyDataType'
        }
        /// <summary>
        /// Test the property 'StringValue'
        /// </summary>
        [Test]
        public void StringValueTest()
        {
            // TODO unit test for the property 'StringValue'
        }
        /// <summary>
        /// Test the property 'IntegerValue'
        /// </summary>
        [Test]
        public void IntegerValueTest()
        {
            // TODO unit test for the property 'IntegerValue'
        }
        /// <summary>
        /// Test the property 'DoubleValue'
        /// </summary>
        [Test]
        public void DoubleValueTest()
        {
            // TODO unit test for the property 'DoubleValue'
        }
        /// <summary>
        /// Test the property 'DateValue'
        /// </summary>
        [Test]
        public void DateValueTest()
        {
            // TODO unit test for the property 'DateValue'
        }

    }

}
