/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocxTableTableFillRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocxTableTableFillRequestTests
    {
        // TODO uncomment below to declare an instance variable for DocxTableTableFillRequest
        //private DocxTableTableFillRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocxTableTableFillRequest
            //instance = new DocxTableTableFillRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocxTableTableFillRequest
        /// </summary>
        [Test]
        public void DocxTableTableFillRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocxTableTableFillRequest
            //Assert.IsInstanceOfType<DocxTableTableFillRequest> (instance, "variable 'instance' is a DocxTableTableFillRequest");
        }


        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'InputFileData'
        /// </summary>
        [Test]
        public void InputFileDataTest()
        {
            // TODO unit test for the property 'InputFileData'
        }
        /// <summary>
        /// Test the property 'TableStartTag'
        /// </summary>
        [Test]
        public void TableStartTagTest()
        {
            // TODO unit test for the property 'TableStartTag'
        }
        /// <summary>
        /// Test the property 'TableEndTag'
        /// </summary>
        [Test]
        public void TableEndTagTest()
        {
            // TODO unit test for the property 'TableEndTag'
        }
        /// <summary>
        /// Test the property 'DataToFillIn'
        /// </summary>
        [Test]
        public void DataToFillInTest()
        {
            // TODO unit test for the property 'DataToFillIn'
        }

    }

}
