/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing DocxSetCustomMetadataPropertiesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocxSetCustomMetadataPropertiesRequestTests
    {
        // TODO uncomment below to declare an instance variable for DocxSetCustomMetadataPropertiesRequest
        //private DocxSetCustomMetadataPropertiesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocxSetCustomMetadataPropertiesRequest
            //instance = new DocxSetCustomMetadataPropertiesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocxSetCustomMetadataPropertiesRequest
        /// </summary>
        [Test]
        public void DocxSetCustomMetadataPropertiesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocxSetCustomMetadataPropertiesRequest
            //Assert.IsInstanceOfType<DocxSetCustomMetadataPropertiesRequest> (instance, "variable 'instance' is a DocxSetCustomMetadataPropertiesRequest");
        }


        /// <summary>
        /// Test the property 'InputFileBytes'
        /// </summary>
        [Test]
        public void InputFileBytesTest()
        {
            // TODO unit test for the property 'InputFileBytes'
        }
        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'PropertiesToSet'
        /// </summary>
        [Test]
        public void PropertiesToSetTest()
        {
            // TODO unit test for the property 'PropertiesToSet'
        }

    }

}
