/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing EditPdfBatchJobCreateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EditPdfBatchJobCreateResultTests
    {
        // TODO uncomment below to declare an instance variable for EditPdfBatchJobCreateResult
        //private EditPdfBatchJobCreateResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EditPdfBatchJobCreateResult
            //instance = new EditPdfBatchJobCreateResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EditPdfBatchJobCreateResult
        /// </summary>
        [Test]
        public void EditPdfBatchJobCreateResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EditPdfBatchJobCreateResult
            //Assert.IsInstanceOfType<EditPdfBatchJobCreateResult> (instance, "variable 'instance' is a EditPdfBatchJobCreateResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Test]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }

    }

}
