/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing FillHandlebarFormField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FillHandlebarFormFieldTests
    {
        // TODO uncomment below to declare an instance variable for FillHandlebarFormField
        //private FillHandlebarFormField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FillHandlebarFormField
            //instance = new FillHandlebarFormField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FillHandlebarFormField
        /// </summary>
        [Test]
        public void FillHandlebarFormFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FillHandlebarFormField
            //Assert.IsInstanceOfType<FillHandlebarFormField> (instance, "variable 'instance' is a FillHandlebarFormField");
        }


        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Test]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'ValueToFill'
        /// </summary>
        [Test]
        public void ValueToFillTest()
        {
            // TODO unit test for the property 'ValueToFill'
        }

    }

}
