/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing GetDocxMetadataPropertiesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetDocxMetadataPropertiesResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetDocxMetadataPropertiesResponse
        //private GetDocxMetadataPropertiesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetDocxMetadataPropertiesResponse
            //instance = new GetDocxMetadataPropertiesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetDocxMetadataPropertiesResponse
        /// </summary>
        [Test]
        public void GetDocxMetadataPropertiesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetDocxMetadataPropertiesResponse
            //Assert.IsInstanceOfType<GetDocxMetadataPropertiesResponse> (instance, "variable 'instance' is a GetDocxMetadataPropertiesResponse");
        }


        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Manager'
        /// </summary>
        [Test]
        public void ManagerTest()
        {
            // TODO unit test for the property 'Manager'
        }
        /// <summary>
        /// Test the property 'ApplicationVersion'
        /// </summary>
        [Test]
        public void ApplicationVersionTest()
        {
            // TODO unit test for the property 'ApplicationVersion'
        }
        /// <summary>
        /// Test the property 'WordCount'
        /// </summary>
        [Test]
        public void WordCountTest()
        {
            // TODO unit test for the property 'WordCount'
        }
        /// <summary>
        /// Test the property 'LineCount'
        /// </summary>
        [Test]
        public void LineCountTest()
        {
            // TODO unit test for the property 'LineCount'
        }
        /// <summary>
        /// Test the property 'ParagraphCount'
        /// </summary>
        [Test]
        public void ParagraphCountTest()
        {
            // TODO unit test for the property 'ParagraphCount'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'CustomProperties'
        /// </summary>
        [Test]
        public void CustomPropertiesTest()
        {
            // TODO unit test for the property 'CustomProperties'
        }
        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

    }

}
