/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing GetXlsxSpecificRowRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetXlsxSpecificRowRequestTests
    {
        // TODO uncomment below to declare an instance variable for GetXlsxSpecificRowRequest
        //private GetXlsxSpecificRowRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetXlsxSpecificRowRequest
            //instance = new GetXlsxSpecificRowRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetXlsxSpecificRowRequest
        /// </summary>
        [Test]
        public void GetXlsxSpecificRowRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetXlsxSpecificRowRequest
            //Assert.IsInstanceOfType<GetXlsxSpecificRowRequest> (instance, "variable 'instance' is a GetXlsxSpecificRowRequest");
        }


        /// <summary>
        /// Test the property 'InputFileBytes'
        /// </summary>
        [Test]
        public void InputFileBytesTest()
        {
            // TODO unit test for the property 'InputFileBytes'
        }
        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'WorksheetToQuery'
        /// </summary>
        [Test]
        public void WorksheetToQueryTest()
        {
            // TODO unit test for the property 'WorksheetToQuery'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
