/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing HtmlThreatLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlThreatLinkTests
    {
        // TODO uncomment below to declare an instance variable for HtmlThreatLink
        //private HtmlThreatLink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlThreatLink
            //instance = new HtmlThreatLink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlThreatLink
        /// </summary>
        [Test]
        public void HtmlThreatLinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlThreatLink
            //Assert.IsInstanceOfType<HtmlThreatLink> (instance, "variable 'instance' is a HtmlThreatLink");
        }


        /// <summary>
        /// Test the property 'LinkUrl'
        /// </summary>
        [Test]
        public void LinkUrlTest()
        {
            // TODO unit test for the property 'LinkUrl'
        }
        /// <summary>
        /// Test the property 'ThreatLevel'
        /// </summary>
        [Test]
        public void ThreatLevelTest()
        {
            // TODO unit test for the property 'ThreatLevel'
        }

    }

}
