/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing HtmlHyperlink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlHyperlinkTests
    {
        // TODO uncomment below to declare an instance variable for HtmlHyperlink
        //private HtmlHyperlink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlHyperlink
            //instance = new HtmlHyperlink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlHyperlink
        /// </summary>
        [Test]
        public void HtmlHyperlinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlHyperlink
            //Assert.IsInstanceOfType<HtmlHyperlink> (instance, "variable 'instance' is a HtmlHyperlink");
        }


        /// <summary>
        /// Test the property 'Anchortext'
        /// </summary>
        [Test]
        public void AnchortextTest()
        {
            // TODO unit test for the property 'Anchortext'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
