/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing HtmlGetRelCanonicalUrlResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlGetRelCanonicalUrlResultTests
    {
        // TODO uncomment below to declare an instance variable for HtmlGetRelCanonicalUrlResult
        //private HtmlGetRelCanonicalUrlResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlGetRelCanonicalUrlResult
            //instance = new HtmlGetRelCanonicalUrlResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlGetRelCanonicalUrlResult
        /// </summary>
        [Test]
        public void HtmlGetRelCanonicalUrlResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlGetRelCanonicalUrlResult
            //Assert.IsInstanceOfType<HtmlGetRelCanonicalUrlResult> (instance, "variable 'instance' is a HtmlGetRelCanonicalUrlResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CanonicalUrl'
        /// </summary>
        [Test]
        public void CanonicalUrlTest()
        {
            // TODO unit test for the property 'CanonicalUrl'
        }

    }

}
