/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing HtmlSsrfThreatCheckResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HtmlSsrfThreatCheckResultTests
    {
        // TODO uncomment below to declare an instance variable for HtmlSsrfThreatCheckResult
        //private HtmlSsrfThreatCheckResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HtmlSsrfThreatCheckResult
            //instance = new HtmlSsrfThreatCheckResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HtmlSsrfThreatCheckResult
        /// </summary>
        [Test]
        public void HtmlSsrfThreatCheckResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HtmlSsrfThreatCheckResult
            //Assert.IsInstanceOfType<HtmlSsrfThreatCheckResult> (instance, "variable 'instance' is a HtmlSsrfThreatCheckResult");
        }


        /// <summary>
        /// Test the property 'IsValid'
        /// </summary>
        [Test]
        public void IsValidTest()
        {
            // TODO unit test for the property 'IsValid'
        }
        /// <summary>
        /// Test the property 'IsThreat'
        /// </summary>
        [Test]
        public void IsThreatTest()
        {
            // TODO unit test for the property 'IsThreat'
        }
        /// <summary>
        /// Test the property 'ThreatLinks'
        /// </summary>
        [Test]
        public void ThreatLinksTest()
        {
            // TODO unit test for the property 'ThreatLinks'
        }

    }

}
