/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing MsgToJpgResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MsgToJpgResultTests
    {
        // TODO uncomment below to declare an instance variable for MsgToJpgResult
        //private MsgToJpgResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MsgToJpgResult
            //instance = new MsgToJpgResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MsgToJpgResult
        /// </summary>
        [Test]
        public void MsgToJpgResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MsgToJpgResult
            //Assert.IsInstanceOfType<MsgToJpgResult> (instance, "variable 'instance' is a MsgToJpgResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'JpgResultPages'
        /// </summary>
        [Test]
        public void JpgResultPagesTest()
        {
            // TODO unit test for the property 'JpgResultPages'
        }

    }

}
