/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing PdfToPngDirectResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PdfToPngDirectResultTests
    {
        // TODO uncomment below to declare an instance variable for PdfToPngDirectResult
        //private PdfToPngDirectResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PdfToPngDirectResult
            //instance = new PdfToPngDirectResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PdfToPngDirectResult
        /// </summary>
        [Test]
        public void PdfToPngDirectResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PdfToPngDirectResult
            //Assert.IsInstanceOfType<PdfToPngDirectResult> (instance, "variable 'instance' is a PdfToPngDirectResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'PngResultPages'
        /// </summary>
        [Test]
        public void PngResultPagesTest()
        {
            // TODO unit test for the property 'PngResultPages'
        }

    }

}
