/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing PptxSplitAdvancedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PptxSplitAdvancedRequestTests
    {
        // TODO uncomment below to declare an instance variable for PptxSplitAdvancedRequest
        //private PptxSplitAdvancedRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PptxSplitAdvancedRequest
            //instance = new PptxSplitAdvancedRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PptxSplitAdvancedRequest
        /// </summary>
        [Test]
        public void PptxSplitAdvancedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PptxSplitAdvancedRequest
            //Assert.IsInstanceOfType<PptxSplitAdvancedRequest> (instance, "variable 'instance' is a PptxSplitAdvancedRequest");
        }


        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Test]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }
        /// <summary>
        /// Test the property 'SlidesPerPresentation'
        /// </summary>
        [Test]
        public void SlidesPerPresentationTest()
        {
            // TODO unit test for the property 'SlidesPerPresentation'
        }

    }

}
