/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing PresentationAdvancedResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PresentationAdvancedResultTests
    {
        // TODO uncomment below to declare an instance variable for PresentationAdvancedResult
        //private PresentationAdvancedResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PresentationAdvancedResult
            //instance = new PresentationAdvancedResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PresentationAdvancedResult
        /// </summary>
        [Test]
        public void PresentationAdvancedResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PresentationAdvancedResult
            //Assert.IsInstanceOfType<PresentationAdvancedResult> (instance, "variable 'instance' is a PresentationAdvancedResult");
        }


        /// <summary>
        /// Test the property 'SlideNumber'
        /// </summary>
        [Test]
        public void SlideNumberTest()
        {
            // TODO unit test for the property 'SlideNumber'
        }
        /// <summary>
        /// Test the property 'PresentationContents'
        /// </summary>
        [Test]
        public void PresentationContentsTest()
        {
            // TODO unit test for the property 'PresentationContents'
        }

    }

}
