/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ReplaceDocxParagraphRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplaceDocxParagraphRequestTests
    {
        // TODO uncomment below to declare an instance variable for ReplaceDocxParagraphRequest
        //private ReplaceDocxParagraphRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplaceDocxParagraphRequest
            //instance = new ReplaceDocxParagraphRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplaceDocxParagraphRequest
        /// </summary>
        [Test]
        public void ReplaceDocxParagraphRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplaceDocxParagraphRequest
            //Assert.IsInstanceOfType<ReplaceDocxParagraphRequest> (instance, "variable 'instance' is a ReplaceDocxParagraphRequest");
        }


        /// <summary>
        /// Test the property 'InputFileBytes'
        /// </summary>
        [Test]
        public void InputFileBytesTest()
        {
            // TODO unit test for the property 'InputFileBytes'
        }
        /// <summary>
        /// Test the property 'InputFileUrl'
        /// </summary>
        [Test]
        public void InputFileUrlTest()
        {
            // TODO unit test for the property 'InputFileUrl'
        }
        /// <summary>
        /// Test the property 'FindString'
        /// </summary>
        [Test]
        public void FindStringTest()
        {
            // TODO unit test for the property 'FindString'
        }
        /// <summary>
        /// Test the property 'MatchCase'
        /// </summary>
        [Test]
        public void MatchCaseTest()
        {
            // TODO unit test for the property 'MatchCase'
        }
        /// <summary>
        /// Test the property 'ReplacementImage'
        /// </summary>
        [Test]
        public void ReplacementImageTest()
        {
            // TODO unit test for the property 'ReplacementImage'
        }

    }

}
