/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing RtfToJpgResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RtfToJpgResultTests
    {
        // TODO uncomment below to declare an instance variable for RtfToJpgResult
        //private RtfToJpgResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RtfToJpgResult
            //instance = new RtfToJpgResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RtfToJpgResult
        /// </summary>
        [Test]
        public void RtfToJpgResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RtfToJpgResult
            //Assert.IsInstanceOfType<RtfToJpgResult> (instance, "variable 'instance' is a RtfToJpgResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'JpgResultPages'
        /// </summary>
        [Test]
        public void JpgResultPagesTest()
        {
            // TODO unit test for the property 'JpgResultPages'
        }

    }

}
