/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing SingleReplaceString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SingleReplaceStringTests
    {
        // TODO uncomment below to declare an instance variable for SingleReplaceString
        //private SingleReplaceString instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SingleReplaceString
            //instance = new SingleReplaceString();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SingleReplaceString
        /// </summary>
        [Test]
        public void SingleReplaceStringInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SingleReplaceString
            //Assert.IsInstanceOfType<SingleReplaceString> (instance, "variable 'instance' is a SingleReplaceString");
        }


        /// <summary>
        /// Test the property 'MatchString'
        /// </summary>
        [Test]
        public void MatchStringTest()
        {
            // TODO unit test for the property 'MatchString'
        }
        /// <summary>
        /// Test the property 'ReplaceString'
        /// </summary>
        [Test]
        public void ReplaceStringTest()
        {
            // TODO unit test for the property 'ReplaceString'
        }
        /// <summary>
        /// Test the property 'MatchCase'
        /// </summary>
        [Test]
        public void MatchCaseTest()
        {
            // TODO unit test for the property 'MatchCase'
        }

    }

}
