/* 
 * convertapi
 *
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Api;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Model;
using Cloudmersive.APIClient.NET.DocumentAndDataConvert.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAndDataConvert.Test
{
    /// <summary>
    ///  Class for testing ZipEncryptionAdvancedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZipEncryptionAdvancedRequestTests
    {
        // TODO uncomment below to declare an instance variable for ZipEncryptionAdvancedRequest
        //private ZipEncryptionAdvancedRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZipEncryptionAdvancedRequest
            //instance = new ZipEncryptionAdvancedRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZipEncryptionAdvancedRequest
        /// </summary>
        [Test]
        public void ZipEncryptionAdvancedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZipEncryptionAdvancedRequest
            //Assert.IsInstanceOfType<ZipEncryptionAdvancedRequest> (instance, "variable 'instance' is a ZipEncryptionAdvancedRequest");
        }


        /// <summary>
        /// Test the property 'InputFileContents'
        /// </summary>
        [Test]
        public void InputFileContentsTest()
        {
            // TODO unit test for the property 'InputFileContents'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'EncryptionAlgorithm'
        /// </summary>
        [Test]
        public void EncryptionAlgorithmTest()
        {
            // TODO unit test for the property 'EncryptionAlgorithm'
        }

    }

}
